### ISSUE TITLE
integration ton bridge error type build with jest

### ISSUE THREAD

**Issue by haunv3** [oraichain/tonbridge-sdk#2]
```ts
import { TonBridgeHandler } from "@oraichain/tonbridge-sdk";
```

```ts
 const wasmBridge = new TonbridgeBridgeClient(client, oraiAddress, TON_BRIDGE_ADAPTER_ORAICHAIN);
        const handler = await TonBridgeHandler.create({
          wasmBridge,
          tonBridge: TON_BRIDGE_ADAPTER,
          tonSender: this.config.tonWallet.sender,
          tonClientParameters: {
            endpoint: "https://toncenter.com/api/v2/jsonRPC",
            apiKey: process.env.TON_API_KEY
          }
});
```

When I integrate the `tonbridge-sdk` version `1.3.2`, I encounter an error like this. I think the issue is related to the build type: `module` or `commonjs`

![Screen Shot 2024-09-05 at 11 14 18](https://github.com/user-attachments/assets/c06f71c0-45a7-4d50-bd63-ccc1eaf6a0c4)

which solution should I use?

**Comment by ducphamle2** [comment]
This is because `vitest` uses ES module by default to transpile and run the tests. However, the `@oraichain/tonbridge-sdk` bundle uses CommonJS -> lead to the above error

**Comment by haunv3** [comment]
> This is because `vitest` uses ES module by default to transpile and run the tests. However, the `@oraichain/tonbridge-sdk` bundle uses CommonJS -> lead to the above error

I think the problem is solved. Thanks 🚀
